name = input("please input the location: ")
new_file = open("C:\\address.bat","w")
new_file.write("set PM=C:\\Users\\WDAGUtilityAccount\\Desktop\\ProcessMonitor\\procmon.exe\n")
new_file.write("start %PM% /AcceptEula /quiet /minimized /backingfile C:\\" + name +".pml   \n")
new_file.write("%PM%  /waitforidle /AcceptEula\n")
new_file.write("start /wait "+ name + "\n")
new_file.write("%PM% /terminate /AcceptEula \n")
new_file.write("%PM% /SaveAs1 C:\\" + name +".xml " + "/Openlog C:\\" + name + ".pml " +  "/quiet /minimized /AcceptEula\n")
new_file.write("%PM% /minimized /terminate /AcceptEula \n")
new_file.close() 
