# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MainUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 616)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-1, 0, 931, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_2.setStyleSheet("color:#FFFFFF;\n"
"font: 9pt \"Microsoft Sans Serif\";\n"
"background-color:#48A1F5;\n"
"border-style:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 891, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.analyseButton = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyseButton.sizePolicy().hasHeightForWidth())
        self.analyseButton.setSizePolicy(sizePolicy)
        self.analyseButton.setMinimumSize(QtCore.QSize(80, 80))
        self.analyseButton.setMaximumSize(QtCore.QSize(80, 80))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/result.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analyseButton.setIcon(icon)
        self.analyseButton.setIconSize(QtCore.QSize(40, 40))
        self.analyseButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.analyseButton.setObjectName("analyseButton")
        self.horizontalLayout.addWidget(self.analyseButton)
        self.fileMonitorButton = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileMonitorButton.sizePolicy().hasHeightForWidth())
        self.fileMonitorButton.setSizePolicy(sizePolicy)
        self.fileMonitorButton.setMinimumSize(QtCore.QSize(80, 80))
        self.fileMonitorButton.setMaximumSize(QtCore.QSize(80, 80))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/文件.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileMonitorButton.setIcon(icon1)
        self.fileMonitorButton.setIconSize(QtCore.QSize(40, 40))
        self.fileMonitorButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.fileMonitorButton.setObjectName("fileMonitorButton")
        self.horizontalLayout.addWidget(self.fileMonitorButton)
        self.regMonitorButton = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regMonitorButton.sizePolicy().hasHeightForWidth())
        self.regMonitorButton.setSizePolicy(sizePolicy)
        self.regMonitorButton.setMinimumSize(QtCore.QSize(80, 80))
        self.regMonitorButton.setMaximumSize(QtCore.QSize(80, 80))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/注册.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.regMonitorButton.setIcon(icon2)
        self.regMonitorButton.setIconSize(QtCore.QSize(40, 40))
        self.regMonitorButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.regMonitorButton.setObjectName("regMonitorButton")
        self.horizontalLayout.addWidget(self.regMonitorButton)
        self.netMonitorButton = QtWidgets.QToolButton(self.layoutWidget)
        self.netMonitorButton.setMinimumSize(QtCore.QSize(80, 80))
        self.netMonitorButton.setMaximumSize(QtCore.QSize(80, 80))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/网络.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.netMonitorButton.setIcon(icon3)
        self.netMonitorButton.setIconSize(QtCore.QSize(40, 40))
        self.netMonitorButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.netMonitorButton.setObjectName("netMonitorButton")
        self.horizontalLayout.addWidget(self.netMonitorButton)
        self.pidButton = QtWidgets.QToolButton(self.layoutWidget)
        self.pidButton.setMinimumSize(QtCore.QSize(80, 80))
        self.pidButton.setMaximumSize(QtCore.QSize(80, 80))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/进程.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pidButton.setIcon(icon4)
        self.pidButton.setIconSize(QtCore.QSize(40, 40))
        self.pidButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pidButton.setObjectName("pidButton")
        self.horizontalLayout.addWidget(self.pidButton)
        self.cpuButton = QtWidgets.QToolButton(self.layoutWidget)
        self.cpuButton.setMinimumSize(QtCore.QSize(80, 80))
        self.cpuButton.setMaximumSize(QtCore.QSize(80, 80))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/cpu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cpuButton.setIcon(icon5)
        self.cpuButton.setIconSize(QtCore.QSize(40, 40))
        self.cpuButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.cpuButton.setObjectName("cpuButton")
        self.horizontalLayout.addWidget(self.cpuButton)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 120, 931, 421))
        self.stackedWidget.setStyleSheet("background-color:#FFFFFF")
        self.stackedWidget.setObjectName("stackedWidget")
        self.cpuPage = QtWidgets.QWidget()
        self.cpuPage.setObjectName("cpuPage")
        self.frame_3 = QtWidgets.QFrame(self.cpuPage)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 141, 421))
        self.frame_3.setStyleSheet("color:#000000;\n"
"font: 9pt \"Microsoft Sans Serif\";\n"
"background-color:#F2F2F2;\n"
"border-style:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 100, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.cpuPage)
        self.graphicsView.setGeometry(QtCore.QRect(140, 0, 791, 421))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.cpuPage)
        self.label.setGeometry(QtCore.QRect(220, 10, 600, 400))
        self.label.setText("")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.cpuPage)
        self.pidPage = QtWidgets.QWidget()
        self.pidPage.setObjectName("pidPage")
        self.treeWidget = QtWidgets.QTreeWidget(self.pidPage)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 931, 421))
        self.treeWidget.setStyleSheet("QScrollBar::handle:vertical {background: #E0E0E0;min-height: 120px}")
        self.treeWidget.setObjectName("treeWidget")
        self.stackedWidget.addWidget(self.pidPage)
        self.textPage = QtWidgets.QWidget()
        self.textPage.setObjectName("textPage")
        self.textBrowser = QtWidgets.QTextBrowser(self.textPage)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 931, 421))
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.textPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionopen)
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pidButton.clicked['bool'].connect(MainWindow.showPidTree)
        self.netMonitorButton.clicked['bool'].connect(MainWindow.showOperator)
        self.regMonitorButton.clicked['bool'].connect(MainWindow.showOperator)
        self.fileMonitorButton.clicked['bool'].connect(MainWindow.showOperator)
        self.analyseButton.clicked['bool'].connect(MainWindow.showOperator)
        self.cpuButton.clicked.connect(MainWindow.showPerformance)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.showCpuorMen)
        self.pushButton.clicked.connect(MainWindow.showCpuorMen)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.analyseButton.setText(_translate("MainWindow", "分析"))
        self.fileMonitorButton.setText(_translate("MainWindow", "文件读写监控"))
        self.regMonitorButton.setText(_translate("MainWindow", "注册表监控"))
        self.netMonitorButton.setText(_translate("MainWindow", "网络监控"))
        self.pidButton.setText(_translate("MainWindow", "进程"))
        self.cpuButton.setText(_translate("MainWindow", "性能"))
        self.pushButton.setText(_translate("MainWindow", "CPU"))
        self.pushButton_2.setText(_translate("MainWindow", "内存"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "进程名称"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "进程pid"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionopen.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


