# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie

class Ui_Open(object):
    def setupUi(self, Open):
        Open.setObjectName("Open")
        Open.resize(800, 500)
        Open.setMinimumSize(QtCore.QSize(800, 500))
        Open.setMaximumSize(QtCore.QSize(800, 500))
        Open.setSizeIncrement(QtCore.QSize(800, 500))
        Open.setBaseSize(QtCore.QSize(800, 500))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Open.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/sandbox.png"))
        Open.setWindowIcon(icon)
        Open.setAutoFillBackground(False)
        Open.setStyleSheet("")
        self.stackedWidget = QtWidgets.QStackedWidget(Open)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.stackedWidget.setStyleSheet("background-color:#FFFFFF")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(0, -10, 301, 511))
        self.frame.setStyleSheet("border-width : 1px;border-color : #2C2C2C;background-color : #393939;color:#BBBBBB;\n"
"font: 10pt \"Microsoft Sans Serif\";\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolButton_10 = QtWidgets.QPushButton(self.frame)
        self.toolButton_10.setGeometry(QtCore.QRect(0, 10, 300, 45))
        self.toolButton_10.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_10.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_10.setObjectName("toolButton_10")
        self.toolButton_14 = QtWidgets.QPushButton(self.frame)
        self.toolButton_14.setGeometry(QtCore.QRect(0, 45, 300, 45))
        self.toolButton_14.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_14.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_14.setObjectName("toolButton_14")
        self.toolButton_13 = QtWidgets.QPushButton(self.frame)
        self.toolButton_13.setGeometry(QtCore.QRect(0, 90, 300, 45))
        self.toolButton_13.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_13.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_13.setObjectName("toolButton_13")
        self.toolButton_12 = QtWidgets.QPushButton(self.frame)
        self.toolButton_12.setGeometry(QtCore.QRect(0, 135, 300, 45))
        self.toolButton_12.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_12.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_12.setObjectName("toolButton_12")
        self.toolButton_11 = QtWidgets.QPushButton(self.frame)
        self.toolButton_11.setGeometry(QtCore.QRect(0, 180, 300, 45))
        self.toolButton_11.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_11.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_11.setObjectName("toolButton_11")
        self.toolButton_18 = QtWidgets.QPushButton(self.frame)
        self.toolButton_18.setGeometry(QtCore.QRect(0, 225, 300, 45))
        self.toolButton_18.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_18.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_18.setObjectName("toolButton_18")
        self.toolButton_17 = QtWidgets.QPushButton(self.frame)
        self.toolButton_17.setGeometry(QtCore.QRect(0, 270, 300, 45))
        self.toolButton_17.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_17.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_17.setObjectName("toolButton_17")
        self.toolButton_16 = QtWidgets.QPushButton(self.frame)
        self.toolButton_16.setGeometry(QtCore.QRect(0, 315, 300, 45))
        self.toolButton_16.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_16.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_16.setObjectName("toolButton_16")
        self.toolButton_15 = QtWidgets.QPushButton(self.frame)
        self.toolButton_15.setGeometry(QtCore.QRect(0, 360, 300, 45))
        self.toolButton_15.setMinimumSize(QtCore.QSize(300, 45))
        self.toolButton_15.setMaximumSize(QtCore.QSize(300, 45))

        self.toolButton_15.setObjectName("toolButton_15")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(300, 0, 501, 501))
        self.frame_2.setStyleSheet("color:#BBBBBB;\n"
"font: 9pt \"Microsoft Sans Serif\";\n"
"background-color:#45474A;\n"
"border-style:none;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 250, 244, 141))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.toolButton.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton.setFont(font)
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton.setStyleSheet("QToolButton:hover{border-color:#45474A;color:#AB5C25}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/文件夹-开 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(20, 20))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_3.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.toolButton_2.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolButton_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolButton_2.setStyleSheet("QToolButton:hover{border-color:#45474A;color:#AB5C25}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/加号1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout_3.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.toolButton_3.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_3.setStyleSheet("QToolButton:hover{border-color:#45474A;color:#AB5C25}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/输入1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout_3.addWidget(self.toolButton_3)
        self.toolButton_4 = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.toolButton_4.setMinimumSize(QtCore.QSize(240, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_4.setStyleSheet("QToolButton:hover{border-color:#45474A;color:#AB5C25}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/运行1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon4)
        self.toolButton_4.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout_3.addWidget(self.toolButton_4)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(140, 320, 241, 30))
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setStyleSheet("QLineEdit{background-color:#FFFFFF;color:#000000}")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(260, 50, 256, 256))
        self.label.setObjectName("label")
        movie = QMovie("./icons/rotating.gif")
        self.label.setMovie(movie)
        movie.start()
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(270, 340, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:none")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_2)
        self.action_Open_Environment_Folders = QtWidgets.QAction(Open)
        self.action_Open_Environment_Folders.setObjectName("action_Open_Environment_Folders")
        self.action_Open_EXE = QtWidgets.QAction(Open)
        self.action_Open_EXE.setObjectName("action_Open_EXE")
        self.action_Manual_Input = QtWidgets.QAction(Open)
        self.action_Manual_Input.setObjectName("action_Manual_Input")
        self.action_Run = QtWidgets.QAction(Open)
        self.action_Run.setObjectName("action_Run")

        self.retranslateUi(Open)
        self.stackedWidget.setCurrentIndex(1)
        self.toolButton.clicked['bool'].connect(self.action_Open_Environment_Folders.trigger)
        self.toolButton_2.clicked['bool'].connect(self.action_Open_EXE.trigger)
        self.lineEdit.returnPressed.connect(self.action_Manual_Input.trigger)
        self.toolButton_4.clicked['bool'].connect(self.action_Run.trigger)
        self.toolButton_3.clicked['bool'].connect(self.lineEdit.show)
        self.lineEdit.returnPressed.connect(self.lineEdit.hide)
        QtCore.QMetaObject.connectSlotsByName(Open)


    def retranslateUi(self, Open):
        _translate = QtCore.QCoreApplication.translate
        Open.setWindowTitle(_translate("Open", "Welcome to Sandbox"))
        self.toolButton_10.setText(_translate("Open", "123"))
        self.toolButton_14.setText(_translate("Open", "123"))
        self.toolButton_13.setText(_translate("Open", "123"))
        self.toolButton_12.setText(_translate("Open", "123"))
        self.toolButton_11.setText(_translate("Open", "123"))
        self.toolButton_18.setText(_translate("Open", "123"))
        self.toolButton_17.setText(_translate("Open", "123"))
        self.toolButton_16.setText(_translate("Open", "123"))
        self.toolButton_15.setText(_translate("Open", "123"))
        self.toolButton.setText(_translate("Open", " Open Environment Folders"))
        self.toolButton_2.setText(_translate("Open", " Open EXE"))
        self.toolButton_3.setText(_translate("Open", "  Manual Input"))
        self.toolButton_4.setText(_translate("Open", " Run In Sandbox"))
        self.pushButton.setText(_translate("Open", "正在分析中"))
        self.action_Open_Environment_Folders.setText(_translate("Open", " Open Environment Folders"))
        self.action_Open_EXE.setText(_translate("Open", " Open EXE"))
        self.action_Manual_Input.setText(_translate("Open", "  Manual Input"))
        self.action_Run.setText(_translate("Open", " Run"))

